package cn.xxx.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-04-27T10:32:50.486+08:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://service.rpms.xxx.cn/", name = "IMantenanceServiceCXF")
@XmlSeeAlso({ObjectFactory.class})
public interface IMantenanceServiceCXF {

    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://service.rpms.xxx.cn/", className = "cn.xxx.client.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://service.rpms.xxx.cn/", className = "cn.xxx.client.UpdateResponse")
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Object arg0
    );

    @WebMethod
    @RequestWrapper(localName = "queryPage", targetNamespace = "http://service.rpms.xxx.cn/", className = "cn.xxx.client.QueryPage")
    @ResponseWrapper(localName = "queryPageResponse", targetNamespace = "http://service.rpms.xxx.cn/", className = "cn.xxx.client.QueryPageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cn.xxx.client.PageList queryPage(
        @WebParam(name = "arg0", targetNamespace = "")
        cn.xxx.client.BaseQuery arg0
    );

    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://service.rpms.xxx.cn/", className = "cn.xxx.client.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://service.rpms.xxx.cn/", className = "cn.xxx.client.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://service.rpms.xxx.cn/", className = "cn.xxx.client.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.rpms.xxx.cn/", className = "cn.xxx.client.AddResponse")
    public void add(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Object arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getAll", targetNamespace = "http://service.rpms.xxx.cn/", className = "cn.xxx.client.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://service.rpms.xxx.cn/", className = "cn.xxx.client.GetAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.Object> getAll();

    @WebMethod
    @RequestWrapper(localName = "queryLimt", targetNamespace = "http://service.rpms.xxx.cn/", className = "cn.xxx.client.QueryLimt")
    @ResponseWrapper(localName = "queryLimtResponse", targetNamespace = "http://service.rpms.xxx.cn/", className = "cn.xxx.client.QueryLimtResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cn.xxx.client.PageList queryLimt(
        @WebParam(name = "arg0", targetNamespace = "")
        cn.xxx.client.MaintenanceQuery arg0
    );

    @WebMethod
    @RequestWrapper(localName = "get", targetNamespace = "http://service.rpms.xxx.cn/", className = "cn.xxx.client.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://service.rpms.xxx.cn/", className = "cn.xxx.client.GetResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Object get(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );
}
