package cn.xxx.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-04-27T10:32:50.524+08:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "MantenanceServiceImplCXFService",
                  wsdlLocation = "http://localhost:80/service/HelloWorld?wsdl",
                  targetNamespace = "http://impl.service.rpms.xxx.cn/")
public class MantenanceServiceImplCXFService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.rpms.xxx.cn/", "MantenanceServiceImplCXFService");
    public final static QName MantenanceServiceImplCXFPort = new QName("http://impl.service.rpms.xxx.cn/", "MantenanceServiceImplCXFPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:80/service/HelloWorld?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MantenanceServiceImplCXFService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:80/service/HelloWorld?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MantenanceServiceImplCXFService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MantenanceServiceImplCXFService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MantenanceServiceImplCXFService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MantenanceServiceImplCXFService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MantenanceServiceImplCXFService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MantenanceServiceImplCXFService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IMantenanceServiceCXF
     */
    @WebEndpoint(name = "MantenanceServiceImplCXFPort")
    public IMantenanceServiceCXF getMantenanceServiceImplCXFPort() {
        return super.getPort(MantenanceServiceImplCXFPort, IMantenanceServiceCXF.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMantenanceServiceCXF
     */
    @WebEndpoint(name = "MantenanceServiceImplCXFPort")
    public IMantenanceServiceCXF getMantenanceServiceImplCXFPort(WebServiceFeature... features) {
        return super.getPort(MantenanceServiceImplCXFPort, IMantenanceServiceCXF.class, features);
    }

}
